from tkinter import*
def checkbox():
    root = Tk()
    root.title("checkbox")
    root.geometry("600x500")
    root.option_add("font", 'tahoma 40 bold')
    frame = Frame(root)
    frame.config(background="cyan")
    frame.place(width=600, height=500,x=0,y=0)
    root.option_add("*foreground", "navy")
    root.option_add("*background", "cyan")
    root.option_add("*Label.font", "tahoma 11 bold underline")
    label1 = Label(frame, text="Your Favorite Sport")
    label1.grid(column=0, row=0, padx=80, pady=10)
    var1 = IntVar()
    c1 = Checkbutton(frame, text="แบดมินตัน", width=50, variable=var1, anchor=CENTER)
    c1.grid(column=0, row=1, padx=80, pady=10)
    var2 = IntVar()
    c2 = Checkbutton(frame, text="เทนนิส", width=50,variable=var2, anchor=CENTER)
    c2.grid(column=0, row=2, padx=80, pady=10)
    var3 = IntVar()
    c3 = Checkbutton(frame, text="ปิงปอง", width=50, variable=var3, anchor=CENTER)
    c3.grid(column=0, row=3, padx=80, pady=10)
    root.mainloop()
checkbox()
